# Site settings
title: carlosrey.es
header-img: img/home-bg.jpg
email: reyescarlos@live.com 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://carlosrey.es"
twitter_username: louspudol
github_username:  carlosreyes
facebook_username:  carloscarlos

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
