# Site settings
title: carlosrey.es
header-img: img/home-bg.jpg
email: reyescarlos@live.com 
description: "Full stack developer from Toronto."
baseurl: ""
url: "http://carlosrey.es"
twitter_username: 
github_username:  carlosreyes
facebook_username:  carloscarlos

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
